Feat/add spine performance
oasis-engine/playground pull request #79
Opened 2021-06-11 08:50 UTC by johanzhu

2021-06-12 07:10 UTC, zhuxudong commented
merge to dev/0.4

2021-06-13 10:43 UTC, GuoLei1990 commented
avatar.png  is still need? @zhuxudong

2021-06-13 10:43 UTC, GuoLei1990 requested changes

2021-06-13 10:43 UTC, GuoLei1990 commented on demos/spine-animation/index.ts
> +cameraEntity.transform.position = new Vector3(0, 0, 60);
use `setPosition()`

2021-06-13 10:43 UTC, GuoLei1990 commented on demos/spine-performance/index.ts
> +Logger.enable();
Delete this

2021-06-15 02:16 UTC, closed without merging